# Copied from icp-bot/backend/domains/mahak/people/mahak/icp/zoho_db.py (read-only reference repo).
# Only imports and plumbing are adapted for Rasa Incanta; the logic is the ICP bot's.
"""Read-only Postgres client against `zoho_data`, the automated ETL replica
of Zoho CRM (Blob Storage -> ADF -> Databricks -> Postgres — see
Database_Guide.md / schema.sql). This module issues SELECT statements only.

The read-only Zoho login already has SELECT-only grants, but this pipeline was
explicitly told never to write back to any source system, so the connection
itself is opened with `default_transaction_read_only=on` as a second,
client-side guarantee independent of the DB-side grants.

Schema confirmed directly against the live database (2026-08-18): 9 tables —
accounts, deals, deal_history, sales_orders, reachout_tracker,
milestone_revenue, project_value_details, team_structure, users. Column
names below are copied from `information_schema.columns`, not guessed from
the field guide.
"""

from __future__ import annotations

import socket
from contextlib import contextmanager
from urllib.parse import parse_qsl, urlencode, urlparse, urlunparse

import psycopg
from psycopg.rows import dict_row

from api.icp.compat import get_settings


def _with_fallback_hostaddr(dsn: str) -> str:
    """Some containerized/sandboxed environments resolve hostnames fine via
    the standard system resolver but fail inside libpq's own getaddrinfo
    call (observed in local dev: `socket.getaddrinfo` succeeds, `psycopg.
    connect` fails with "Name or service not known" on the same host). If
    that happens, pre-resolve the host with Python's resolver and pass the
    IP as `hostaddr` — libpq still uses `host` separately for the TLS SNI
    and certificate check, so this doesn't weaken the TLS verification."""
    parsed = urlparse(dsn)
    host = parsed.hostname
    if not host:
        return dsn
    try:
        ip = socket.getaddrinfo(host, None)[0][4][0]
    except OSError:
        return dsn
    query = dict(parse_qsl(parsed.query))
    query.setdefault("hostaddr", ip)
    return urlunparse(parsed._replace(query=urlencode(query)))


@contextmanager
def get_connection():
    settings = get_settings()
    dsn = settings.zoho_pg_dsn
    connect_kwargs = dict(connect_timeout=15, options="-c default_transaction_read_only=on", row_factory=dict_row)
    try:
        conn = psycopg.connect(dsn, **connect_kwargs)
    except psycopg.OperationalError as exc:
        if "Name or service not known" not in str(exc):
            raise
        conn = psycopg.connect(_with_fallback_hostaddr(dsn), **connect_kwargs)
    try:
        yield conn
    finally:
        conn.close()


ACCOUNT_COLUMNS = (
    "id, account_name, phone, website, billing_street, billing_city, "
    "billing_state, billing_zip, billing_country, client_code, "
    "created_time, modified_time"
)


def find_accounts_by_name(name_variants: list[str], limit: int = 20) -> list[dict]:
    """ILIKE match against `accounts.account_name` for each of the caller's
    name variants (icp-skill.md §0.1 step 1 — spelling/legal-suffix
    variants, root-word match, etc. are generated by entity_resolver.py,
    not here)."""
    variants = [v.strip() for v in name_variants if v and v.strip()]
    if not variants:
        return []
    with get_connection() as conn, conn.cursor() as cur:
        clauses = " OR ".join(["account_name ILIKE %s"] * len(variants))
        params = [f"%{v}%" for v in variants]
        cur.execute(
            f"SELECT {ACCOUNT_COLUMNS} FROM accounts WHERE {clauses} "
            "ORDER BY modified_time DESC NULLS LAST LIMIT %s",
            (*params, limit),
        )
        return cur.fetchall()


def get_account(account_id: int) -> dict | None:
    with get_connection() as conn, conn.cursor() as cur:
        cur.execute(f"SELECT {ACCOUNT_COLUMNS} FROM accounts WHERE id = %s", (account_id,))
        return cur.fetchone()


def list_all_accounts() -> list[dict]:
    """Every account's id/name/modified_time — 9,388 rows on the live DB,
    cheap to pull in full. `entity_resolver.py` uses this for client-side
    fuzzy matching (misspellings like "Sobha" vs "Shobha" don't share an
    ILIKE substring, so a plain WHERE clause can't find them — see
    CHECKLIST.md). Postgres fuzzy-search extensions (pg_trgm,
    fuzzystrmatch) are available but not installed on this replica, and
    installing one would be a schema-level write this pipeline isn't
    allowed to make."""
    with get_connection() as conn, conn.cursor() as cur:
        cur.execute("SELECT id, account_name, modified_time FROM accounts")
        return cur.fetchall()


def list_all_deal_names() -> list[dict]:
    """Every deal's id/name/account_id/stage/modified_time, for the same
    client-side fuzzy-matching reason as `list_all_accounts` — icp-skill.md
    §0.1 step 3's "fuzzy-match on deal name, independent of account" catches
    a Potential whose account link is missing or wrong."""
    with get_connection() as conn, conn.cursor() as cur:
        cur.execute("SELECT id, deal_name, account_id, stage, modified_time FROM deals")
        return cur.fetchall()


def find_deals_by_account_ids(account_ids: list[int]) -> list[dict]:
    if not account_ids:
        return []
    with get_connection() as conn, conn.cursor() as cur:
        cur.execute(
            "SELECT * FROM deals WHERE account_id = ANY(%s) ORDER BY modified_time DESC NULLS LAST",
            (account_ids,),
        )
        return cur.fetchall()


def get_deal(deal_id: int) -> dict | None:
    with get_connection() as conn, conn.cursor() as cur:
        cur.execute("SELECT * FROM deals WHERE id = %s", (deal_id,))
        return cur.fetchone()


def get_deal_history(deal_id: int) -> list[dict]:
    with get_connection() as conn, conn.cursor() as cur:
        cur.execute(
            "SELECT stage, modified_time, moved_to_stage, stage_duration_days "
            "FROM deal_history WHERE deal_id = %s ORDER BY modified_time ASC",
            (deal_id,),
        )
        return cur.fetchall()


def get_reachouts(deal_id: int) -> list[dict]:
    with get_connection() as conn, conn.cursor() as cur:
        cur.execute(
            "SELECT reachout_date, client_contact_name, designation, contact_role, "
            "email, reachout_medium, remarks FROM reachout_tracker "
            "WHERE deal_id = %s ORDER BY reachout_date ASC NULLS LAST",
            (deal_id,),
        )
        return cur.fetchall()


def find_won_deals_by_account_ids(account_ids: list[int]) -> list[dict]:
    """Practus-history classification (§1): `stage = 'Client Won'` deals for
    this company's account(s)."""
    if not account_ids:
        return []
    with get_connection() as conn, conn.cursor() as cur:
        cur.execute(
            "SELECT id, account_id, deal_name, stage, services, industry_type, "
            "date_converted_to_client FROM deals "
            "WHERE account_id = ANY(%s) AND stage = 'Client Won'",
            (account_ids,),
        )
        return cur.fetchall()


def find_won_deals_by_industry(industry: str) -> list[dict]:
    """P1 (icp-skill.md STEP 3): "5+ confirmed clients in the industry"
    counts confirmed Practus clients across the WHOLE CRM, not just this
    one account's own deals -- a case-insensitive exact match on
    `industry_type`, since that field is a BD-picked category label, not
    free text to fuzzy-search."""
    if not industry:
        return []
    with get_connection() as conn, conn.cursor() as cur:
        cur.execute(
            "SELECT d.id, d.account_id, a.account_name, d.deal_name, d.industry_type "
            "FROM deals d JOIN accounts a ON a.id = d.account_id "
            "WHERE d.stage = 'Client Won' AND lower(d.industry_type) = lower(%s)",
            (industry,),
        )
        return cur.fetchall()


def find_all_won_deals() -> list[dict]:
    """Every Client Won deal across the whole CRM, industry_type included --
    unlike find_won_deals_by_industry(), not scoped to one target industry.
    Feeds P1's broader "confirmed clients by industry" breakdown
    (practus_history.confirmed_client_industry_breakdown()), which lets the
    narrative honestly describe adjacent-industry breadth even when the
    exact target industry has zero confirmed clients."""
    with get_connection() as conn, conn.cursor() as cur:
        cur.execute(
            "SELECT d.id, d.account_id, a.account_name, d.industry_type "
            "FROM deals d JOIN accounts a ON a.id = d.account_id "
            "WHERE d.stage = 'Client Won'"
        )
        return cur.fetchall()


def find_lost_deals_by_account_ids(account_ids: list[int]) -> list[dict]:
    """Gate 3 input: prior lost pursuits and whether a reason was captured."""
    if not account_ids:
        return []
    with get_connection() as conn, conn.cursor() as cur:
        cur.execute(
            "SELECT id, account_id, deal_name, created_time, date_client_lost, "
            "reason_for_loss, specify_reason_for_lost, potential_rating, "
            "contact_id FROM deals "
            "WHERE account_id = ANY(%s) AND stage = 'Client Lost' "
            "ORDER BY date_client_lost ASC NULLS LAST",
            (account_ids,),
        )
        return cur.fetchall()


def find_user_by_name_fragment(name: str, limit: int = 10) -> list[dict]:
    """EP/EL/TL name lookups (P3 team-fielded checks) against `users`."""
    if not name or not name.strip():
        return []
    with get_connection() as conn, conn.cursor() as cur:
        cur.execute(
            "SELECT id, full_name, email, role_name, profile_name, sbu, team, status "
            "FROM users WHERE full_name ILIKE %s AND status = 'Active' LIMIT %s",
            (f"%{name.strip()}%", limit),
        )
        return cur.fetchall()


def get_sales_orders_by_account(account_id: int) -> list[dict]:
    with get_connection() as conn, conn.cursor() as cur:
        cur.execute(
            "SELECT id, so_code, status, total_value, tenure_in_months, "
            "mandate_start_date, mandate_end_date, engagement_leader, sbu "
            "FROM sales_orders WHERE account_id = %s ORDER BY so_creation_date DESC NULLS LAST",
            (account_id,),
        )
        return cur.fetchall()


def get_team_structure_by_so(so_id: int) -> list[dict]:
    with get_connection() as conn, conn.cursor() as cur:
        cur.execute(
            "SELECT engagement_partner_1, engagement_leader_1, engagement_leader_2, "
            "el1_pct, el2_pct, ep1_pct FROM team_structure WHERE so_id = %s",
            (so_id,),
        )
        return cur.fetchall()
