"""One-off: write the shared ICP Postgres schema to docs/ICP_Postgres_Schema.md.

Reads ICP_SHARED_DB_URL (repo-root .env locally, or the environment), connects with sslmode=require,
and reads only information_schema for the `icp` schema: columns, keys and foreign keys. It never
selects from any icp table, so no run_files blob is touched, and it never prints the URL.

    python scripts/dump_icp_schema.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import psycopg
from psycopg.rows import dict_row

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from api.config import get_settings  # noqa: E402

OUT = ROOT / "docs" / "ICP_Postgres_Schema.md"

COLUMNS = """
SELECT table_name, column_name, ordinal_position, data_type, udt_name, character_maximum_length,
       numeric_precision, numeric_scale, is_nullable, column_default
FROM information_schema.columns
WHERE table_schema = 'icp'
ORDER BY table_name, ordinal_position"""

KEYS = """
SELECT tc.table_name, tc.constraint_name, tc.constraint_type, kcu.column_name,
       ccu.table_name AS references_table, ccu.column_name AS references_column
FROM information_schema.table_constraints tc
JOIN information_schema.key_column_usage kcu
  ON kcu.constraint_schema = tc.constraint_schema AND kcu.constraint_name = tc.constraint_name
LEFT JOIN information_schema.constraint_column_usage ccu
  ON ccu.constraint_schema = tc.constraint_schema AND ccu.constraint_name = tc.constraint_name
 AND tc.constraint_type = 'FOREIGN KEY'
WHERE tc.table_schema = 'icp' AND tc.constraint_type IN ('PRIMARY KEY', 'FOREIGN KEY', 'UNIQUE')
ORDER BY tc.table_name, tc.constraint_type, tc.constraint_name, kcu.ordinal_position"""


def type_of(c: dict) -> str:
    t = c["udt_name"] if c["data_type"] in ("USER-DEFINED", "ARRAY") else c["data_type"]
    if c["character_maximum_length"]:
        t += f"({c['character_maximum_length']})"
    elif c["data_type"] == "numeric" and c["numeric_precision"]:
        t += f"({c['numeric_precision']},{c['numeric_scale'] or 0})"
    return t


def main() -> int:
    url = get_settings().icp_shared_db_url.strip()
    if not url:
        print("ICP_SHARED_DB_URL is not set (add it to the repo-root .env, or export it).", file=sys.stderr)
        return 1
    try:
        with psycopg.connect(url, sslmode="require", connect_timeout=10, row_factory=dict_row) as conn:
            columns = conn.execute(COLUMNS).fetchall()
            keys = conn.execute(KEYS).fetchall()
    except Exception as exc:  # the message can echo the host; the URL itself is never printed
        print(f"Could not read the schema ({type(exc).__name__}).", file=sys.stderr)
        return 1
    if not columns:
        print("The icp schema has no columns this account can see.", file=sys.stderr)
        return 1

    tables: dict[str, list[dict]] = {}
    for c in columns:
        tables.setdefault(c["table_name"], []).append(c)
    lines = ["# ICP Postgres schema (`icp`)", "",
             "Generated by `scripts/dump_icp_schema.py` from `information_schema`. Column names and types",
             "only, no data. Do not edit by hand; rerun the script.", ""]
    for table, cols in tables.items():
        lines += [f"## icp.{table}", "", "| # | Column | Type | Null | Default |", "|---|---|---|---|---|"]
        for c in cols:
            default = (c["column_default"] or "").replace("|", "\\|")
            lines.append(f"| {c['ordinal_position']} | `{c['column_name']}` | {type_of(c)} | "
                         f"{'yes' if c['is_nullable'] == 'YES' else 'no'} | {('`' + default + '`') if default else ''} |")
        mine = [k for k in keys if k["table_name"] == table]
        if mine:
            lines += ["", "Keys:"]
            for k in mine:
                target = f" -> icp.{k['references_table']}.{k['references_column']}" if k["references_table"] else ""
                lines.append(f"- {k['constraint_type'].lower()} `{k['constraint_name']}`: `{k['column_name']}`{target}")
        lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}: {len(tables)} tables, {len(columns)} columns.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
