"""contact persona cache

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-25 15:47:07.810075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_persona',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_key', sa.String(length=400), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('persona', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('facts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_persona', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_persona_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_persona_contact_key'), ['contact_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_persona', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_persona_contact_key'))
        batch_op.drop_index(batch_op.f('ix_contact_persona_computed_at'))

    op.drop_table('contact_persona')
    # ### end Alembic commands ###
