"""setu case study contexts and embeddings

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-28 16:54:39.346826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setu_case_study_contexts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('case_study_name', sa.String(length=300), nullable=False),
    sa.Column('generated_context', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setu_case_study_contexts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setu_case_study_contexts_source_hash'), ['source_hash'], unique=True)

    op.create_table('setu_case_study_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('case_study_name', sa.String(length=300), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('embedding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hash', 'model', name='uq_setu_case_study_embeddings_hash_model')
    )
    with op.batch_alter_table('setu_case_study_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setu_case_study_embeddings_source_hash'), ['source_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setu_case_study_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setu_case_study_embeddings_source_hash'))

    op.drop_table('setu_case_study_embeddings')
    with op.batch_alter_table('setu_case_study_contexts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setu_case_study_contexts_source_hash'))

    op.drop_table('setu_case_study_contexts')
    # ### end Alembic commands ###
