"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 05:35:57.016583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zoho_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('account_name', sa.String(length=300), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('board', sa.String(length=20), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('city_state', sa.String(length=200), nullable=True),
    sa.Column('lead_source', sa.String(length=200), nullable=True),
    sa.Column('ep_involved', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('el_involved', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stage_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zoho_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zoho_id')
    )
    op.create_table('runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_week_start'), ['week_start'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('context_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('account_fit', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stakeholder', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('conversation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('capability', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('deal_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('gaps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'deal_id')
    )
    with op.batch_alter_table('context_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_cards_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_cards_run_id'), ['run_id'], unique=False)

    op.create_table('deal_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('own_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start', 'deal_id', 'user_id')
    )
    with op.batch_alter_table('deal_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_reviews_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_reviews_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_reviews_week_start'), ['week_start'], unique=False)

    op.create_table('deal_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('board', sa.String(length=20), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'deal_id')
    )
    with op.batch_alter_table('deal_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_snapshots_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_snapshots_run_id'), ['run_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('objective', sa.String(length=20), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('why_now', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('proof', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sme', sa.String(length=200), nullable=True),
    sa.Column('effort', sa.String(length=10), nullable=True),
    sa.Column('treasury_ref', sa.String(length=20), nullable=True),
    sa.Column('gaps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_user_id'), ['user_id'], unique=False)

    op.create_table('user_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    with op.batch_alter_table('user_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_aliases_user_id'), ['user_id'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['deal_reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'recommendation_id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_recommendation_id'), ['recommendation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_review_id'), ['review_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_review_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_recommendation_id'))

    op.drop_table('decisions')
    with op.batch_alter_table('user_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_aliases_user_id'))

    op.drop_table('user_aliases')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_run_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_deal_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('deal_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_snapshots_run_id'))
        batch_op.drop_index(batch_op.f('ix_deal_snapshots_deal_id'))

    op.drop_table('deal_snapshots')
    with op.batch_alter_table('deal_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_reviews_week_start'))
        batch_op.drop_index(batch_op.f('ix_deal_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_deal_reviews_deal_id'))

    op.drop_table('deal_reviews')
    with op.batch_alter_table('context_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_cards_run_id'))
        batch_op.drop_index(batch_op.f('ix_context_cards_deal_id'))

    op.drop_table('context_cards')
    op.drop_table('users')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_week_start'))

    op.drop_table('runs')
    op.drop_table('deals')
    # ### end Alembic commands ###
